- moriodata:
    info: "Collects metrics from Elasticsearch nodes on Linux systems"
    vars:
      METRICS_LINUX_ELASTICSEARCH_METRICSETS:
        dflt:
          - node
          - node_stats
          - cluster_stats
          - index_summary
          - index_recovery
        info: The metricsets to collect on every tick
      METRICS_LINUX_ELASTICSEARCH_API_KEY:
        dflt: ""
        info: The API key to connect to the Elasticsearch API (formatted as key:secret)
      METRICS_LINUX_ELASTICSEARCH_CAS:
        dflt: []
        info: A list of paths to certificates of trusted CAs
      METRICS_LINUX_ELASTICSEARCH_HOSTS:
        dflt: ["http://localhost:9200"]
        info: The (list of) host(s) to collect metrics from (as url)
      METRICS_LINUX_ELASTICSEARCH_PASSWORD:
        dflt: ""
        info: The password (for METRICS_LINUX_ELAsTICSEARCH_USERNAME) to connect to the Elasticsearch API
      METRICS_LINUX_ELASTICSEARCH_USERNAME:
        dflt: ""
        info: The username to connect to the Elasticsearch API

- module: elasticsearch
  period: "{| MORIO_TICK |}"
  metricsets: {|{ METRICS_LINUX_ELASTICSEARCH_METRICSETS }|}
  hosts: {|{ METRICS_LINUX_ELASTICSEARCH_HOSTS }|}
  ssl.certificate_authorities: {|{ METRICS_LINUX_ELASTICSEARCH_CAS }|}
  index_recovery.active_only: true
# Include username if it is set
{|#METRICS_LINUX_ELASTICSEARCH_USERNAME|}
  username: {|{ METRICS_LINUX_ELASTICSEARCH_USERNAME }|}
{|/METRICS_LINUX_ELASTICSEARCH_USERNAME|}
# Include password if it is set
{|#METRICS_LINUX_ELASTICSEARCH_PASSWORD|}
  password: {|{ METRICS_LINUX_ELASTICSEARCH_PASSWORD }|}
{|/METRICS_LINUX_ELASTICSEARCH_PASSWORD|}
# Include api_key if it is set
{|#METRICS_LINUX_ELASTICSEARCH_API_KEY|}
  api_key: {|{ METRICS_LINUX_ELASTICSEARCH_API_KEY }|}
{|/METRICS_LINUX_ELASTICSEARCH_API_KEY|}

# Shards are hard to consume the way the Elasticsearch module handles
# them as there is 1 event per shard. This is a side-effect of the
# shards API entrypoint returning a top-level array. So even if we
# pull them manually, Metricbeat will turn each entry in an event.
# So instead, we grab the data from the routing table in the cluster state.
- module: http
  metricsets:
    - json
  period: "{| MORIO_TICK |}"
  hosts: {|{ METRICS_LINUX_ELASTICSEARCH_HOSTS }|}
  ssl.certificate_authorities: {|{ METRICS_LINUX_ELASTICSEARCH_CAS }|}
  namespace: "morio.elasticsearch"
  path: "/_cluster/state"
  query:
    metric: "nodes.routing_table"
# Include username if it is set
{|#METRICS_LINUX_ELASTICSEARCH_USERNAME|}
  username: {|{ METRICS_LINUX_ELASTICSEARCH_USERNAME }|}
{|/METRICS_LINUX_ELASTICSEARCH_USERNAME|}
# Include password if it is set
{|#METRICS_LINUX_ELASTICSEARCH_PASSWORD|}
  password: {|{ METRICS_LINUX_ELASTICSEARCH_PASSWORD }|}
{|/METRICS_LINUX_ELASTICSEARCH_PASSWORD|}
# Include api_key if it is set
  processors:
    - drop_fields:
        fields:
          - morio.elasticsearch.nodes_versions
        ignore_missing: true
    - add_labels:
        labels:
          morio.dataset: shardstate
