- moriodata:
    info: "Collects Docker metrics on Linux systems"
    vars:
      METRICS_LINUX_DOCKER_METRICSETS_ALWAYS:
        dflt:
          - container
          - event
          - healthcheck
          - info
        info: The metricsets to collect on every tick
      METRICS_LINUX_DOCKER_SOCKET:
        dflt: "unix:///var/run/docker.sock"
        info: Location of the Docker socket

- module: docker
  period: "{| MORIO_TICK |}"
  metricsets: {|{ METRICS_LINUX_DOCKER_METRICSETS_ALWAYS }|}
  hosts: [ {|{ METRICS_LINUX_DOCKER_SOCKET }|} ]
